# Generated by Django 5.1.5 on 2025-04-21 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarian', '0002_book_is_active_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('borrowed', 'Borrowed'), ('deleted', 'Deleted')], default='available', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('reader', 'Читатель'), ('librarian', 'Библиотекарь')], default='reader', max_length=20),
        ),
    ]
