# Generated by Django 5.1.5 on 2025-04-27 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarian', '0004_remove_book_is_active_author_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookreturn',
            name='fine',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
