# Generated by Django 5.1.5 on 2025-06-23 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarian', '0007_book_category_book_description_alter_user_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('textbook', 'Учебник'), ('manual', 'Методичка'), ('tutorial', 'Пособие'), ('fiction', 'Художественная'), ('science', 'Научная'), ('publicism', ' Публицистика'), ('other', 'Другое')], default='other', max_length=20),
        ),
    ]
